### ISSUE TITLE
main 함수의 parameter 정의

### ISSUE THREAD

**Issue by JiwoonKim** [depromeet/question-ranking#5]
main.js 파일 내의 main함수가 다음과 같이 하나의 인자만 받도록 정의 되어있는데 반해,
main(mainFoldedHeight, mainStrechedHeight) 
실행될 때는 다음과 같이 인자를 하나만 전달받습니다.
const main = function changeRankingHeight(foldedHeight) 
혹시 오류가 있는 것인가요?

**Comment by yongseongjeon** [comment]
앗... 오류가 맞습니다... 죄송합니다...
main 함수를 정의할 때 main(mainFoldedHeight) 다음과 같이 하나의 인자만 받는 것으로 정의하도록 수정하겠습니다.
리뷰해주셔서 감사합니다.

**Comment by JiwoonKim** [comment]
넵! 알겠습니다! 제가 바로 반영해서 수정하겠습니다!
