### ISSUE TITLE
changeRankingHeight함수와  questionRankingTopThreeTextMoreOrFold함수의 차이

### ISSUE THREAD

**Issue by JiwoonKim** [depromeet/question-ranking#6]
main으로 부르는 changeRankingHeight(mainFoldedHeight) 함수와 
questionRanking 으로 부르는 questionRankingTopThreeTextMoreOrFold() 함수
두 차이가 무엇인가요?

전체적으로 코드에 코멘트가 없어서 읽기가 어렵습니다ㅠㅜ

일단 제가 코멘트를 추가 중이어서 저 두 함수의 기능 차이만 알려주시면 될 것 같아요!

**Comment by yongseongjeon** [comment]
앗... 코멘트를 달아두었어야 했는데 우선 죄송합니다...

changeRankingHeight(mainFoldedHeight) 함수는 상단의 Question Ranking이 접거나 펴지는것에 따라서 question contents의 높이를 가변적으로 변경해주는 함수입니다. (question contents는 가운데에 위치한 질문이 등록되는 부분입니다.)

questionRankingTopThreeTextMoreOrFold() 함수는 Question Ranking이 펴진 상태에서 질문이 길 경우 우측에 
생기는 more이나 fold 버튼을 눌렀을 때 question contents의 높이를 가변적으로 변경해주는 함수입니다.

너무 정신없게 써놔서 죄송합니다. ㅠㅠ

**Comment by JiwoonKim** [comment]
넵! 확인했습니다!
