### ISSUE TITLE
main.js 내 dim 함수의 코드 리팩토링

### ISSUE THREAD

**Issue by JiwoonKim** [depromeet/question-ranking#7]
main.js 내 dim 함수의 코드 내용에서 
$textarea.keyup(() => { ...} 이 두 번 반복됩니다.
혹시 하나의 함수로 합치지 않고 기능을 두 번 반복하는 이유가 있나요?

**Comment by yongseongjeon** [comment]
아니요... 하나로 합치는게 맞는 것 같습니다... 감사합니다...

**Comment by JiwoonKim** [comment]
넵! 알겠습니다! 제가 반영해서 올릴게요!
