### ISSUE TITLE
main 페이지 랭킹 순위 별 이미지 오류

### ISSUE THREAD

**Issue by JiwoonKim** [depromeet/question-ranking#8]
main 페이지 랭킹 순위 내의 별을 비교해보면,
세 번째 별은 깔끔하게 나오는데 반해, 첫번째랑 두번째가 이미지가 겹친 것처럼 나옵니다.

**Comment by yongseongjeon** [comment]
<img width="295" alt="스크린샷 2019-04-24 오후 5 01 44" src="https://user-images.githubusercontent.com/47478821/56642709-01fc4580-66b3-11e9-9e88-c89b04bf7a66.png">
위의 스크린샷은 제플린에서 가져왔습니다.

제 추측으로는 1등, 별 3개 2등 별, 2개 3등, 별 1개일 것으로 생각했습니다.
아니면 선명도를 말씀하시는 건가요? 제가 질문 이해를 잘 했는지 모르겠네요.

**Comment by JiwoonKim** [comment]
아 저는 이미지가 여러개 겹친 것으로 생각했습니다!

**Comment by JiwoonKim** [comment]
일단 오류가 아님을 확인했으니, 디자이너님께 여쭈어보겠습니다!

**Comment by yongseongjeon** [comment]
넵!!
